Repository marcosdosea/CuidaPet, pull requests merged in 2025-06, with the labels that each got.

#26 Telas de alta fidelidade mobile atualizadas com os tamanhos de fontes apropriados
  Requisitos/Desktop - Alta Fidelidade/D001 - Tela de login.png
  Requisitos/Desktop - Alta Fidelidade/D002 - Consultar Pet.png
  Requisitos/Desktop - Alta Fidelidade/D003 - Manter Agendamento- Atendente.png
  Requisitos/Desktop - Alta Fidelidade/D004 - Criar Agendamento - Atendente.png
  Requisitos/Desktop - Alta Fidelidade/D005 - Manter Doença - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D006 - Manter Doença - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D007 - Manter Espécie (Consultar)- Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D008 - Manter Espécie (Criar)- Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D009- Manter Estabelecimentos - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D010 - Manter Estabelecimentos - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D011 - Manter Funcionários - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D012 - Manter Funcionários - Gerente-1.png
  Requisitos/Desktop - Alta Fidelidade/D012 - Manter Funcionários - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D013 - Manter Produtos (Consultar) - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D014 - Manter Produtos (Criar) - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D015 - Manter Raças (Consultar) - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D016 - Manter Raças (criar) - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D017 - Manter Vacinas (Consultar) - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D018 - Manter Vacina (criar) - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D019 - Menu - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D020 - Menu - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D021 - Vacinar Pet e Consultar Pet - Veterinário.png
  Requisitos/Desktop - Alta Fidelidade/D022 - Vacinar Pet - Veterinário.png
  Requisitos/Desktop - Alta Fidelidade/D023 - Vender Produtos - Atendente.png
  Requisitos/Mobile - Alta Fidelidade/Carrinho - Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M001 - Consultar Estabelecimento - Dentro do Petshop - Clinica e Petshop.png
  Requisitos/Mobile - Alta Fidelidade/M002 - Consultar Estabelecimento - Dentro do Petshop - Clinica e Petshop.png
  Requisitos/Mobile - Alta Fidelidade/M002 - Consultar Estabelecimento - Dentro do Petshop.png
  Requisitos/Mobile - Alta Fidelidade/M003 - Consultar Estabelecimentos - Clínicas.png
  Requisitos/Mobile - Alta Fidelidade/M004 - Consultar Estabelecimentos - PetShops.png
  Requisitos/Mobile - Alta Fidelidade/M006 - Manter Agendamento - Agendar.png
  Requisitos/Mobile - Alta Fidelidade/M007 - Manter Agendamentos (Solicitados) - Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M010 - Manter Tutor - Cadastrar.png
  Requisitos/Mobile - Alta Fidelidade/M011 - Manter Tutor - Login.png
  Requisitos/Mobile - Alta Fidelidade/M012 - Manter Tutor - Perfil do Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M013 - Pedidos - Tutor-1.png
  Requisitos/Mobile - Alta Fidelidade/M013 - Pedidos - Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M013 - Pets- Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M014 - Notificações - Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M015 - Consultar Estabelecimentos - Produtos.png
  Requisitos/Mobile - Alta Fidelidade/M015 - Tela Principal.png
Labels: documentation

#25 Telas de alta fidelidade atualizadas e transferidas para o figma principal conforme issues #23 e #10
  Requisitos/Desktop - Alta Fidelidade/D001 - Tela de login.png
  Requisitos/Desktop - Alta Fidelidade/D002 - Consultar Pet.png
  Requisitos/Desktop - Alta Fidelidade/D003 - Manter Agendamento- Atendente.png
  Requisitos/Desktop - Alta Fidelidade/D004 - Criar Agendamento - Atendente.png
  Requisitos/Desktop - Alta Fidelidade/D005 - Manter Doença - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D006 - Manter Doença - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D007 - Manter Espécie (Consultar)- Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D008 - Manter Espécie (Criar)- Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D009- Manter Estabelecimentos - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D010 - Manter Estabelecimentos - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D011 - Manter Funcionários - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D012 - Manter Funcionários - Gerente-1.png
  Requisitos/Desktop - Alta Fidelidade/D012 - Manter Funcionários - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D013 - Manter Produtos (Consultar) - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D014 - Manter Produtos (Criar) - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D015 - Manter Raças (Consultar) - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D016 - Manter Raças (criar) - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D017 - Manter Vacinas (Consultar) - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D018 - Manter Vacina (criar) - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D019 - Menu - Administrador.png
  Requisitos/Desktop - Alta Fidelidade/D020 - Menu - Gerente.png
  Requisitos/Desktop - Alta Fidelidade/D021 - Vacinar Pet e Consultar Pet - Veterinário.png
  Requisitos/Desktop - Alta Fidelidade/D022 - Vacinar Pet - Veterinário.png
  Requisitos/Desktop - Alta Fidelidade/D023 - Vender Produtos - Atendente.png
Labels: documentation, fix

#34 Aplicar a paleta de cores para o Mobile
  Requisitos/Mobile - Alta Fidelidade/Carrinho - Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M001 - Consultar Estabelecimento - Dentro do Petshop - Clinica e Petshop.png
  Requisitos/Mobile - Alta Fidelidade/M002 - Consultar Estabelecimento - Dentro do Petshop - Clinica e Petshop.png
  Requisitos/Mobile - Alta Fidelidade/M002 - Consultar Estabelecimento - Dentro do Petshop.png
  Requisitos/Mobile - Alta Fidelidade/M003 - Consultar Estabelecimentos - Clínicas.png
  Requisitos/Mobile - Alta Fidelidade/M004 - Consultar Estabelecimentos - PetShops.png
  Requisitos/Mobile - Alta Fidelidade/M006 - Manter Agendamento - Agendar.png
  Requisitos/Mobile - Alta Fidelidade/M007 - Manter Agendamentos (Solicitados) - Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M010 - Manter Tutor - Cadastrar.png
  Requisitos/Mobile - Alta Fidelidade/M011 - Manter Tutor - Login.png
  Requisitos/Mobile - Alta Fidelidade/M012 - Manter Tutor - Perfil do Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M013 - Pedidos - Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M013 - Pets- Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M014 - Notificações - Tutor.png
  Requisitos/Mobile - Alta Fidelidade/M015 - Consultar Estabelecimentos - Produtos.png
  Requisitos/Mobile - Alta Fidelidade/M015 - Tela Principal.png
Labels: enhancement
